// SPDX-License-Identifier: MPL-2.0
/**
 * Page seals - every English /info page as a signed C2PA asset (plans/105 section 7, M5).
 *
 * C2PA 2.4 section A.7 makes an HTML document a first-class signable asset, and gives it
 * two carriers. This module implements the one the spec itself prefers (section A.7.1:
 * "the use of an external manifest via the link element is preferred"): the page
 * carries ONE stable element,
 *
 *     <link rel="c2pa-manifest" href="/info/<slug>.c2pa" type="application/c2pa">
 *
 * and the Manifest Store lives beside it as `/info/<slug>.c2pa` - section 11.4's external
 * manifest, "an acceptable model for providing provenance", served with the JUMBF
 * media type `application/c2pa` (see the repo-root vercel.json header rule).
 *
 * ── Three rules the spec fixes, and this module obeys rather than re-decides ──
 *
 * 1. WHOLE-DOCUMENT HASH, NO EXCLUSION. section A.7.1.3: "For an external link element…
 *    the data hash assertion shall have no exclusion range; the hash shall be
 *    computed over the entire document." That is what `buildExternalC2paStore`
 *    (engine/src/c2pa.ts) builds, so there is no two-pass offset dance here - the
 *    manifest never enters the bytes it binds.
 * 2. SIGN LAST. section A.7.1.3's note: any process that re-serializes the HTML
 *    invalidates the binding, "by design". So sealing runs AFTER every page has
 *    been written, over the bytes read back off disk - never over a string the
 *    build still intends to touch. {@link sealPages} refuses to sign a page whose
 *    final bytes do not already reference the sidecar it is about to write, which
 *    turns that ordering rule into a check instead of a comment.
 * 3. AT MOST ONE ASSOCIATION. section A.7.1: a document must not carry both a `<link>`
 *    and a `<script type="application/c2pa">`. Banked art is inlined STRIPPED
 *    (docs/docs-art.ts), so the page's own `<link>` is its only carrier and stays
 *    the only one.
 *
 * ── CHANGED-ONLY is the law ──────────────────────────────────────────────────
 *
 * Every signature over identical bytes differs (ECDSA nonce + a fresh timestamp),
 * so an unconditional re-sign rewrites 53 binary files on every build - including
 * every incremental `--watch` rebuild - which is how a provenance record becomes
 * noise nobody reads. A page is re-signed only when its seal would say something
 * different: its bytes changed, or its component set did (see below). Otherwise
 * the existing sidecar is left byte-identical and is not written at all.
 *
 * (Plan section 7 reasoned from "/info is committed". It is not: shells/web/.gitignore
 * has ignored the built pages, shots and indexes for a long time, and the sidecars
 * are ignored beside them - a credential for bytes the repo does not hold would be
 * a record nobody can check. The rule stands on its own merits either way, and it
 * is what makes un-ignoring them a safe decision rather than a churn decision.)
 *
 * ── Ingredients: the page's credential CONTAINS its components' ──────────────
 *
 * Plan section 7's ratified shape is "one seal for the page, ingredients disclose the
 * parts": each screenshot and each banked masthead/figure the page references is
 * already signed on its own, and its manifest travels into the page's store as a
 * `c2pa.ingredient.v3` entry. The verifier's existing chain walk then derives a
 * component's AI origin without a single new line of verdict logic - a masthead
 * generated by a model surfaces on the PAGE report through the chain, and the
 * page's own claim never has to restate a claim it did not make.
 *
 * That is also why change detection asks TWO questions, not one. A re-captured
 * screenshot is re-signed with a new manifest label, so a page whose own bytes did
 * not move can still be describing components that no longer exist. The recorded
 * ingredient labels are read back out of the existing sidecar and compared with
 * the ones on disk; a mismatch re-seals. The alternative - hash the page and hope
 * - leaves a credential quietly naming files nobody serves any more.
 *
 * ── What this deliberately does NOT do ───────────────────────────────────────
 *
 * ENGLISH ONLY, this wave. A locale page carrying a link to a sidecar that does
 * not exist reads as "references an external manifest… could not be checked" (a
 * FAILURE row), and pointing 26 locales at the English sidecar would be worse: a
 * hash mismatch, i.e. "this document was modified". The 26 × 53 sidecar question
 * is a decision for Andy, not a default (plans/105-m345 report, C1).
 *
 * And no verdict is claimed anywhere on the page: nothing in /info says a third
 * party can read these bindings today, because no third-party implementation
 * does yet (plan section 10). This module ships machinery.
 */
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { decodeCbor, parseC2paStore, prepareC2paIngredient } from '../engine/src/c2pa-extract.ts';
import { C2PA_SPEC_VERSION, buildExternalC2paStore } from '../engine/src/c2pa.ts';
import { verifyC2pa } from '../engine/src/c2pa-verify.ts';
import { C2PA_CHECK } from '../engine/src/c2pa-verdict.ts';
import { buildExportC2paOpts, type ExportC2paOpts } from '../packages/node-shell/src/c2pa-opts.ts';

/** The sidecar's extension. `.c2pa` is the conventional external-manifest suffix
 *  and matches the `application/c2pa` media type section 11.4 requires. */
export const SEAL_EXT = '.c2pa';

/**
 * Credential window. Long for the same reason the banked art's is
 * (scripts/sign-docs-art.ts): a page that nobody edits keeps its sidecar
 * untouched for years, and a 365-day window would make every reader after month
 * 13 see "expired" on a document that never changed. The window is not a trust
 * signal here anyway - the key is ephemeral and self-signed, which every verifier
 * reports as untrusted by design, and honestly so.
 */
export const PAGE_CREDENTIAL_DAYS = 3650;

/** The served URL of a page's sidecar. Stable across builds - it is part of the
 *  page's own bytes, so it must never be derived from anything that moves. */
export function pageSealHref(slug: string): string {
  return `/info/${slug}${SEAL_EXT}`;
}

/**
 * The one element a sealed page carries, section A.7.1.2 verbatim: `rel="c2pa-manifest"`
 * in the head, `href` to the store. `type` "should be included but is not
 * required for discovery; the validator shall match on the rel attribute alone" - 
 * included, because a served file with a media type and a link element that
 * agrees is what makes the pair readable by something that is not us.
 */
export function pageSealLink(slug: string): string {
  return `<link rel="c2pa-manifest" href="${pageSealHref(slug)}" type="application/c2pa">`;
}

/** A page to seal: its slug, the file the build just wrote, and the facts the
 *  claim records about where it came from. */
export interface SealTarget {
  slug: string;
  /** Absolute path to the built HTML. */
  path: string;
  /** Human title for the claim (the page's own title). */
  title?: string;
  /** The markdown source this page was rendered from, e.g. `docs/exporting.md`. */
  source?: string;
}

export interface SealRun {
  /** Sidecars written this run. */
  signed: string[];
  /** Sealed already, and still true - left byte-identical. */
  kept: string[];
  /** `check: true` only: what a real run would have written. */
  wouldSign: string[];
  /** Sidecars deleted because no sealed page claims them any more. */
  removed: string[];
  /** Pages that could not be sealed, with the reason. Never throws the build. */
  failed: Array<{ slug: string; reason: string }>;
}

export interface SealPagesOptions {
  /** The built site root - `shells/web/public/info`. */
  outDir: string;
  targets: SealTarget[];
  /** Report what would change, write nothing. The churn guard's mode. */
  check?: boolean;
  log?: (line: string) => void;
  warn?: (line: string) => void;
}

// ── Components ───────────────────────────────────────────────────────────────

/**
 * The served files this page REFERENCES - screenshots and banked art, the two
 * kinds of credentialed component a docs page has.
 *
 * Read off attributes, and with the stylesheet removed first, because the inline
 * CSS carries selectors like `img[src*="/info/shots/"]` - a substring scan would
 * turn a style rule into a claimed ingredient. A component is something the page
 * points AT, so an attribute value is the only honest source.
 */
const COMPONENT_REF = /\b(?:src|href|data-shot|data-shot-dark|data-copy-src)\s*=\s*"(\/info\/(?:shots|mastheads|figures)\/[A-Za-z0-9._-]+)"/g;

export function pageComponentRefs(html: string): string[] {
  const body = html.replace(/<style>[\s\S]*?<\/style>/g, ' ');
  const out: string[] = [];
  const seen = new Set<string>();
  for (const m of body.matchAll(COMPONENT_REF)) {
    const ref = m[1]!;
    if (seen.has(ref)) continue;      // one ingredient per file, however often it is used
    seen.add(ref);
    out.push(ref);
  }
  return out;
}

type PageIngredient = NonNullable<ExportC2paOpts['ingredients']>[number];

/** Component path → its ingredient (or null: an uncredentialed or missing file).
 *  A build asks for the same ~340 files once per page; the reads are 50 MB. */
export type ComponentCache = Map<string, PageIngredient | null>;

/**
 * Every credentialed component the page references, in document order, as
 * ingredients ready for the store.
 *
 * `dc:title` is the component's served PATH, not the title off its own claim: all
 * 155 screenshots share the claim title "URL Screenshot", so a page listing
 * seventeen of them would list the same word seventeen times. The path names the
 * exact file and a reader can fetch it - which is what an ingredient title is for.
 *
 * `relationship: componentOf` (not `parentOf`): the page was not derived FROM the
 * screenshot, it is composed WITH it - the same relationship the shots pipeline
 * uses for a genAI bitmap it frames.
 */
export function collectPageIngredients(
  html: string,
  outDir: string,
  cache: ComponentCache = new Map(),
): PageIngredient[] {
  const out: PageIngredient[] = [];
  for (const ref of pageComponentRefs(html)) {
    let ing = cache.get(ref);
    if (ing === undefined) {
      ing = null;
      try {
        const bytes = new Uint8Array(readFileSync(resolve(outDir, ref.replace(/^\/info\//, ''))));
        const found = prepareC2paIngredient(bytes);
        if (found) ing = { ...found, title: ref, relationship: 'componentOf' };
      } catch { /* missing or unreadable component — the page still seals */ }
      cache.set(ref, ing);
    }
    if (ing) out.push(ing);
  }
  return out;
}

/** `c2pa.ingredient.v3`, its version suffixes, and the `__N` repeats the writer
 *  uses when a store preserves more than one (engine/src/c2pa.ts). */
const INGREDIENT_LABEL = /^c2pa\.ingredient(\.v\d+)?(__\d+)?$/;

const cborGet = (m: unknown, k: string): unknown => (m instanceof Map ? m.get(k) : undefined);

/**
 * The component manifests an EXISTING sidecar says it contains - read back out of
 * its own ingredient assertions.
 *
 * This is the half of change detection the page hash cannot see. A manifest label
 * is a fresh `urn:uuid` per signing, so a re-captured screenshot changes its
 * label; comparing the recorded set with the set on disk is what catches "the
 * page is identical but two of its components were replaced".
 *
 * Returns null when the store cannot be parsed at all - which is itself a reason
 * to re-sign, and is treated as one.
 */
export function recordedComponentLabels(store: Uint8Array): string[] | null {
  try {
    const parts = parseC2paStore(store);
    const labels: string[] = [];
    for (const a of parts.assertions) {
      if (!INGREDIENT_LABEL.test(a.label)) continue;
      const url = cborGet(cborGet(decodeCbor(a.content), 'activeManifest'), 'url');
      if (typeof url === 'string') labels.push(url.replace(/^self#jumbf=\/c2pa\//, ''));
    }
    return labels;
  } catch {
    return null;
  }
}

const sameSet = (a: string[], b: string[]): boolean => {
  if (a.length !== b.length) return false;
  const left = [...a].sort();
  const right = [...b].sort();
  return left.every((v, i) => v === right[i]);
};

// ── Change detection ─────────────────────────────────────────────────────────

/**
 * Does this sidecar still tell the truth about this page?
 *
 * Deliberately narrower than "does it verify", for the reason
 * scripts/sign-docs-art.ts gives: an ephemeral self-signed key is reported
 * untrusted BY DESIGN, and a certificate that has aged out is still a true record
 * of bytes that never changed. Re-signing on either would rewrite every sidecar on
 * the site on a schedule nobody chose. The two checks that actually mean "these bytes
 * are the bytes that were signed" are the hard binding and the claim signature - 
 * plus, here, the component set the store names.
 */
export async function sealHolds(
  pageBytes: Uint8Array,
  store: Uint8Array,
  expectedLabels: string[],
): Promise<boolean> {
  try {
    const report = await verifyC2pa(pageBytes, { externalManifest: store });
    const ok = (code: string): boolean => report.checks.some((c) => c.code === code && c.ok);
    if (!report.found) return false;
    if (!ok(C2PA_CHECK.assertionDataHashMatch) || !ok(C2PA_CHECK.claimSignatureValidated)) return false;
    const recorded = recordedComponentLabels(store);
    return recorded !== null && sameSet(recorded, expectedLabels);
  } catch {
    return false;
  }
}

// ── Signing ──────────────────────────────────────────────────────────────────

/**
 * The claim a page seal makes. Nothing here is inferred: the slug, the source
 * markdown and the locale are facts the build holds, and they are recorded as the
 * "recipe" of the page exactly as the shots pipeline records a capture's URL and
 * viewport - so /verify can say what this document was rendered from.
 *
 * No `aiDisclosure`. The pages are written by people; the default `c2pa.created`
 * action's `digitalCreation` source type is the true statement, and section 18.28.3 is
 * explicit that no disclosure is attached to it. A banked masthead's model
 * reaches the reader through the INGREDIENT chain (plan section 7), which is a claim its
 * own signer made - not one this build restates on its behalf.
 */
function pageC2paOpts(target: SealTarget, ingredients: PageIngredient[]): ExportC2paOpts {
  const row = (id: string, value: string): Record<string, unknown> =>
    ({ id, type: 'text', value, isDirty: true, label: id });
  const model = [
    row('page', `/info/${target.slug}.html`),
    ...(target.source ? [row('source', target.source)] : []),
    row('lang', 'en'),
  ] as unknown as Parameters<typeof buildExportC2paOpts>[0]['model'];
  const opts = buildExportC2paOpts({
    surface: 'docs',
    manifest: { id: 'docs-page', name: target.title || target.slug },
    model,
    format: 'html',
    days: PAGE_CREDENTIAL_DAYS,
    specVersion: C2PA_SPEC_VERSION,
    ...(ingredients.length ? { ingredients } : {}),
  });
  return {
    ...opts,
    environment: {
      ...(opts.environment as Record<string, unknown>),
      // Lolly's own namespace - the only place "what kind of thing is this" is
      // recorded as a plain fact (section 10.2.3.2 reserves claim_generator_info for the
      // claim's generator, which is Lolly, not the document).
      artifact: 'docs-page',
      page: `/info/${target.slug}.html`,
    },
  };
}

type SealOutcome =
  | { outcome: 'signed' | 'kept' | 'wouldSign' }
  | { outcome: 'failed'; reason: string };

/**
 * Seal one page, or leave its sidecar exactly as it is.
 *
 * Reads the bytes back OFF DISK rather than taking the string the build rendered:
 * the hash must cover what was actually written, including whatever the file
 * system and the encoder did to it, or the first reader to fetch the page finds a
 * binding over bytes that only ever existed in memory.
 */
async function sealOne(
  target: SealTarget,
  outDir: string,
  cache: ComponentCache,
  check: boolean,
): Promise<SealOutcome> {
  let bytes: Uint8Array;
  let html: string;
  try {
    bytes = new Uint8Array(readFileSync(target.path));
    html = Buffer.from(bytes).toString('utf-8');
  } catch (err) {
    return { outcome: 'failed', reason: `could not read the built page (${(err as Error).message})` };
  }
  // section A.7.1.3's ordering rule, enforced. A sidecar beside a page that does not
  // point at it is a file nobody can find from the asset - and a page whose link
  // was emitted after the hash would be a binding over bytes that no longer
  // exist. Both are caught by asking the page itself, once, before signing.
  if (!html.includes(`href="${pageSealHref(target.slug)}"`)) {
    return { outcome: 'failed', reason: `the built page carries no <link rel="c2pa-manifest" href="${pageSealHref(target.slug)}">` };
  }
  const ingredients = collectPageIngredients(html, outDir, cache);
  const labels = ingredients.map((i) => i.activeLabel);
  const sidecar = resolve(outDir, `${target.slug}${SEAL_EXT}`);
  if (existsSync(sidecar)) {
    try {
      if (await sealHolds(bytes, new Uint8Array(readFileSync(sidecar)), labels)) return { outcome: 'kept' };
    } catch { /* unreadable sidecar — re-sign it */ }
  }
  if (check) return { outcome: 'wouldSign' };
  try {
    const store = await buildExternalC2paStore(bytes, pageC2paOpts(target, ingredients));
    writeFileSync(sidecar, store);
    return { outcome: 'signed' };
  } catch (err) {
    return { outcome: 'failed', reason: `signing failed (${(err as Error).message})` };
  }
}

/**
 * Seal every page in `targets`, and delete the sidecars that no page claims.
 *
 * Runs as the LAST build step over the written site (section A.7.1.3), and never throws:
 * a page that cannot be sealed is reported, loudly, and the build finishes. A
 * missing sidecar is self-healing - the next build signs it - whereas a build that
 * died two thirds of the way through a locale sweep because one page moved is a
 * site nobody can publish.
 */
export async function sealPages(o: SealPagesOptions): Promise<SealRun> {
  const { outDir, targets, check = false } = o;
  const log = o.log ?? ((l: string) => console.log(l));
  const warn = o.warn ?? ((l: string) => console.warn(l));
  const run: SealRun = { signed: [], kept: [], wouldSign: [], removed: [], failed: [] };
  const cache: ComponentCache = new Map();

  for (const target of targets) {
    const res = await sealOne(target, outDir, cache, check);
    if (res.outcome === 'failed') {
      run.failed.push({ slug: target.slug, reason: res.reason });
      warn(`⚠  seal ${target.slug}: ${res.reason}`);
    } else if (res.outcome === 'signed') run.signed.push(target.slug);
    else if (res.outcome === 'kept') run.kept.push(target.slug);
    else run.wouldSign.push(target.slug);
  }

  // Orphans: a retired slug leaves its sidecar behind, and a `.c2pa` beside no
  // page is a credential for a document nobody serves. Only ever the top level of
  // /info (English pages), only ever `.c2pa`, and never in check mode.
  const claimed = new Set(targets.map((t) => `${t.slug}${SEAL_EXT}`));
  let present: string[] = [];
  try { present = readdirSync(outDir).filter((f) => f.endsWith(SEAL_EXT)); } catch { /* no site yet */ }
  for (const file of present) {
    if (claimed.has(file)) continue;
    run.removed.push(file);
    if (!check) rmSync(resolve(outDir, file), { force: true });
  }

  const counts = check
    ? `${run.kept.length} current, ${run.wouldSign.length} would re-sign`
    : `${run.signed.length} signed, ${run.kept.length} unchanged`;
  log(`✓  /info/*.c2pa page seals (${counts}${run.removed.length ? `, ${run.removed.length} orphaned` : ''})`);
  return run;
}

/**
 * The sealed pages already on disk - every top-level `/info/*.html` that carries a
 * seal link pointing at its own slug.
 *
 * Exists for the churn guard (tests/docs-page-seal.test.ts) and for anything that
 * needs to ask the BUILT site what it claims, rather than being told: a test that
 * took the page list from build.ts would be re-asserting the build's own opinion.
 * Redirect stubs have no seal link, so they are not sealed and not listed.
 */
export function discoverSealTargets(outDir: string): SealTarget[] {
  let files: string[] = [];
  try { files = readdirSync(outDir).filter((f) => f.endsWith('.html')).sort(); } catch { return []; }
  const out: SealTarget[] = [];
  for (const file of files) {
    const slug = file.slice(0, -'.html'.length);
    const path = resolve(outDir, file);
    let html: string;
    try { html = readFileSync(path, 'utf-8'); } catch { continue; }
    // The slug and the href have to AGREE. A page linking a sidecar that is not
    // its own is not a sealed page - signing it would write a store into a file
    // that page never points at.
    if (!html.includes(`href="${pageSealHref(slug)}"`)) continue;
    out.push({ slug, path });
  }
  return out;
}
